# This is a basic workflow to help you get started with Actions

name: tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '00 4 * * 3'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: scripts/install_docker.sh

      - name: Run tests
        run: make docker-test
